# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
jobs:
  ci:
    # don't run on pull request from ourselves
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/reusable-SKELETONS.yml
  check:  # This job does nothing and is only used for the branch protection
    if: always()
    runs-on: ubuntu-22.04
    needs:
      - ci
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
...
