# vim: set ft=yaml ts=2 expandtab:
#
# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

name: CI

on:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:

  ci:
    runs-on: ubuntu-22.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      # Set ANSIBLE_COLLECTIONS_PATH restrictive, adjust it where necessary
      ANSIBLE_COLLECTIONS_PATH: "$HOME/.ansible/collections"

    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          path: skeletons

      - name: Create a directory for ansible collections
        run: mkdir -p ansible_collections

      - name: install shellcheck
        run: sudo apt-get install shellcheck

      - name: install ansible-lint
        run: pip install ansible-lint

      - name: yamllint
        working-directory: skeletons
        run: yamllint -s .

      # https://github.com/ansible/ansible/pull/82624
      - name: No "masked" files do exist in ansible-collection-skeleton
        working-directory: skeletons
        run: |
            while read f
            do
                if test -f "$f".j2;
                then
                    false
                fi
            # we search the whole directory tree for now,
            # change that when it cause troubles
            #
            done < <(find . -type f)

      - name: Collection | create a new collection with our skeleton
        working-directory: ansible_collections
        run: |
          ansible-galaxy collection init --collection-skeleton ../skeletons/ansible-collection-skeleton local.ci
          ansible-galaxy collection install -r local/ci/requirements.yml

      - name: Collection | lint
        working-directory: ansible_collections/local/ci
        run: |
          yamllint -s .
          ansible-lint -x "galaxy[version-incorrect],galaxy[tags]"

      - name: Collection | sanity
        working-directory: ansible_collections/local/ci
        run: |
          ansible-test sanity

      - name: Collectionrole | create a new role
        working-directory: ansible_collections
        run: |
          ansible-galaxy role init --role-skeleton ../skeletons/ansible-collection-role-skeleton role1 --init-path local/ci/roles
          cat - >local/ci/playbooks/ci.yml << EOF
          ---
          - name: A ci playbook
            hosts: localhost
            roles:
              - role: local.ci.role1
          EOF

      - name: Collection | lint
        working-directory: ansible_collections/local/ci
        run: |
          test -f "roles/role1/tasks/main.yml"
          pwd
          tree "$GITHUB_WORKSPACE/ansible_collections"
          cat roles/role1/meta/main.yml
          yamllint -s .
          ansible-lint -x "galaxy[version-incorrect],galaxy[tags]"

      - name: Collection | sanity
        working-directory: ansible_collections/local/ci
        run: ansible-test sanity

      - name: Collection | run playbook
        working-directory: ansible_collections/local/ci
        env:
          ANSIBLE_COLLECTIONS_PATH: "$GITHUB_WORKSPACE:${{ env.ANSIBLE_COLLECTIONS_PATH }}"
        run: ansible-playbook playbooks/ci.yml

...
